# Generated by Django 4.2.6 on 2023-11-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allnews",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
