# Generated by Django 4.2.6 on 2023-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0002_allnews_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allnews",
            name="time",
            field=models.DateTimeField(default="2023-11-02T10:52:00Z"),
        ),
    ]
