# Generated by Django 4.2.6 on 2023-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0003_alter_allnews_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="allnews",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="index"),
        ),
    ]
