# Generated by Django 4.2.6 on 2023-11-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0003_alter_allnews_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="allnews",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="allnews",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
