# Generated by Django 4.2.6 on 2023-11-07 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0004_allnews_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allnews",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="allnews",
            name="time",
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 10, 52)),
        ),
    ]
