# Generated by Django 4.2.6 on 2023-11-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0005_remove_allnews_image_url_alter_allnews_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allnews",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
