# Generated by Django 4.2.6 on 2023-11-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0006_alter_allnews_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allnews",
            name="image",
        ),
        migrations.AddField(
            model_name="allnews",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
