# Generated by Django 4.2.6 on 2023-11-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0007_remove_allnews_image_allnews_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="allnews",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="index"),
        ),
    ]
