# Generated by Django 4.2.6 on 2023-11-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0010_remove_allnews_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allnews",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
