# Generated by Django 4.2.6 on 2023-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mynewsapp", "0012_allnews_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="allnews",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
